### ISSUE TITLE
test.sh fails in Python 2.7.3

### ISSUE THREAD

**Issue by lsb** [rasky/gcs#1] opened 2012-09-11 20:09 UTC
I'm on Ubuntu 12 LTS (not sure if it matter), stock Python install, and running ./test.sh all of the words return false queries, the three misspelled words and the three properly spelled words. 

The query in C++ returned identical results. Trying to build "table.gcs" failed:

./gcs build ../samples/words.english
numwords: 639653
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by rasky** [comment] 2012-09-11 21:42
Hi, can you please provide a backtrace of the C++ crash? I can't reproduce it. I can recompile the C++ version on Ubuntu 12.04 and it works as expect (build + query).

The Python version seems broken indeed, must be a stupid thing. Looking into it.

**Comment by rasky** [comment] 2012-09-11 21:57
Python version is now fixed. I'll look into the C++ crash once you provide the traceback. Thanks!

**Comment by lsb** [comment] 2012-09-11 21:59
After modifying the make.sh to include -g and remove -O3 (as well as -std=c++0x), and running in gdb, it looks like it's failing at values.reserve(N*P).  I'm getting the following backtrace:

#0  0xb7fdd424 in __kernel_vsyscall ()
#1  0xb7d581ef in raise () from /lib/i386-linux-gnu/tls/i686/nosegneg/libc.so.6
#2  0xb7d5b835 in abort () from /lib/i386-linux-gnu/tls/i686/nosegneg/libc.so.6
#3  0xb7f9a13d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#4  0xb7f97ed3 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#5  0xb7f97f0f in std::terminate() () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#6  0xb7f9805e in __cxa_throw () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#7  0xb7f9867f in operator new(unsigned int) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#8  0x0804b6ea in __gnu_cxx::new_allocator<unsigned int>::allocate (this=0xbfffee38, __n=655004672) at /usr/include/c++/4.6/ext/new_allocator.h:92
#9  0x0804afb2 in std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_M_allocate (this=0xbfffee38, __n=655004672) at /usr/include/c++/4.6/bits/stl_vector.h:150
#10 0x0804a9d9 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_allocate_and_copy<std::move_iterator<unsigned int*> > (this=0xbfffee38, __n=655004672, __first=..., __last=...)
    at /usr/include/c++/4.6/bits/stl_vector.h:1052
#11 0x0804a773 in std::vector<unsigned int, std::allocator<unsigned int> >::reserve (this=0xbfffee38, __n=655004672) at /usr/include/c++/4.6/bits/vector.tcc:76
#12 0x08049c3a in GCSBuilder::GCSBuilder (this=0xbfffee30, _n=639653, _p=1024) at gcs.cpp:143
#13 0x0804943e in main (argc=3, argv=0xbffff254) at main.cpp:70

**Comment by rasky** [comment] 2012-09-11 22:14
I was reserving too much memory, and probably filling your 32-bit Ubuntu address space (I have only 64-bit instances around, where the problem was not visibile). It should now be fixed.

BTW, I just realized that the hash function is slightly wrong because using the modulus _does_ affect the uniform distribution; so the resulting set is slightly suboptimal for the given inputs. If you want to fix it, be my guest and submit a pull request.

**Closed as completed** 2012-09-11 22:14 UTC

**Comment by lsb** [comment] 2012-09-11 22:17
Cool, thanks very much! Will look into it.
